server:
  port: 6000
spring:
  application:
    name: crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    password: 123456
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka